### PR TITLE
Check the permission of the uami

### LINKED ISSUE #44: Check permission of user-assigned managed identity
We should check the required permissions of the user-assigned managed identity (uami) before deploying the Azure resources, fail fast if the required permissions are not granted to the uami.

### PR DESCRIPTION
**Pull request by majguo**
## Description

The PR is to resolve the following issues:
* Resolve #44

## Change summary

* Enhance deployment script `create-sp.sh` to check if Contributor role (or Owner role) is granted to the uami before deploying Azure resources

## Testing

The following test cases have already been passed before opening the PR:

* The uami has no access to the subscription: Deployment failed fast
* The uami has Reader role in the subscription: Deployment failed fast
* The uami has Contributor role in the subscription: Deployment succeeded

Here is the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewazure-liberty-aro) for live testing.

Signed-off-by: Jianguo Ma <jiangma@microsoft.com>

### CODE REVIEW

File: src/main/scripts/create-sp.sh [hunk 1]
```diff
@@ -14,6 +14,29 @@
...
+    exit 1
+fi
+
+# Query principal Id of the user-assigned managed identity
+principalId=$(az identity show --ids ${AZ_SCRIPTS_USER_ASSIGNED_IDENTITY} --query "principalId" -o tsv)
+
+# Check if the user assigned managed identity has Contributor or Owner role
+roleLength=$(az role assignment list --assignee ${principalId} | jq '.[] | [select(.roleDefinitionName=="Contributor" or .roleDefinitionName=="Owner")] | length')
+if [ ${roleLength} -lt 1 ]; then
+    echo "The user-assigned managed identity must has Contributor or Owner role in the subscription, please check ${AZ_SCRIPTS_USER_ASSIGNED_IDENTITY}" >&2
```
Comment (git4rk) [inline src/main/scripts/create-sp.sh:36]: `must has` -> `must have`

Comment (majguo) [reply src/main/scripts/create-sp.sh]: Fixed in commit c978cf5.

**Review by git4rk — APPROVED** [review]
